# Generated by Django 3.2.15 on 2025-06-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneFamily',
            fields=[
                ('name', models.CharField(db_index=True, max_length=120, primary_key=True, serialize=False, verbose_name='基因家族名称')),
                ('gene_number', models.BigIntegerField(verbose_name='基因数量')),
                ('gene_list', models.JSONField(default=list, verbose_name='基因列表')),
            ],
        ),
    ]
