# Generated by Django 3.2.15 on 2025-06-23 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genefamily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.CharField(db_index=True, max_length=120, primary_key=True, serialize=False, unique=True, verbose_name='基因ID')),
                ('species', models.CharField(db_index=True, max_length=120, verbose_name='物种')),
                ('chrom', models.CharField(db_index=True, max_length=120, verbose_name='染色体')),
                ('start', models.BigIntegerField(verbose_name='起始位置')),
                ('end', models.BigIntegerField(verbose_name='终止位置')),
                ('cds_sequence', models.TextField(verbose_name='CDS序列')),
                ('protein_length', models.BigIntegerField(verbose_name='蛋白序列长度')),
                ('protein_sequence', models.TextField(verbose_name='蛋白质序列')),
                ('mature_protein_sequence', models.TextField(verbose_name='蛋白质成熟序列')),
                ('function', models.TextField(verbose_name='功能注释结果')),
                ('uniprot_kb', models.CharField(db_index=True, max_length=120, verbose_name='关联UniProtKB  ID')),
                ('ensembl_url', models.CharField(db_index=True, max_length=1024, verbose_name='关联ensemble地址')),
                ('gene_network_url', models.CharField(db_index=True, max_length=1024, verbose_name='关联基因网络地址')),
                ('subcellular_localization', models.CharField(db_index=True, max_length=1024, verbose_name='关联亚细胞定位地址')),
                ('gene_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genefamily.genefamily', verbose_name='基因家族名称')),
            ],
        ),
        migrations.CreateModel(
            name='CoExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene2', models.CharField(db_index=True, max_length=120, verbose_name='Gene2')),
                ('pcc', models.CharField(db_index=True, max_length=120, verbose_name='PCC')),
                ('mr', models.CharField(db_index=True, max_length=120, verbose_name='MR')),
                ('gene1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.gene', verbose_name='Gene1')),
            ],
        ),
    ]
